name = "malta-tenders"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "91140990538410712862953981830703"
ENVIRONMENT = "production"
APP_URL = "https://malta-tenders.pages.dev"
CRON_SECRET = "c8b74a9f3d6e2150b9ac7f85m4p6q9r2"

[[d1_databases]]
binding = "DB"
database_name = "malta-tenders-db"
database_id = "3d0aafdb-c44b-4bf5-8c11-8b9ecc8d317a"

[[kv_namespaces]]
binding = "CACHE"
id = "e550ae7153834f4ebb6a913093b48f86"

[triggers]
crons = ["0 6 * * *"]

[build]
command = "npm run build"

[build.upload]
format = "directory"

[pages]
pages_build_output_dir = ".next"
